In [11]:
import pandas as pd

load dataset

In [12]:
base_path= "/Users/hdpriyo/Desktop/Paper/dataset/"

Student_info=pd.read_csv(base_path + "studentInfo.csv")
Student_assessment= pd.read_csv(base_path + "studentAssessment.csv")
Student_registration= pd.read_csv(base_path + "studentRegistration.csv")
student_vle=pd.read_csv(base_path + "studentVle_short.csv")


marge dataset

In [13]:
merge1= pd.merge (Student_info, Student_assessment, on="id_student", how="left" )


In [14]:
merge2= pd.merge (merge1, Student_registration, on=["id_student", "code_module", "code_presentation"], how="left")


In [15]:
final_merge= pd.merge (merge2,student_vle, on=["id_student", "code_module", "code_presentation"], how="left")


In [16]:
final_merge.to_csv("merge_final_dataset_copy.csv", index=False)

In [17]:
final_merge["burnout"]=0

In [18]:
final_merge.to_csv("burnout_0.csv", index=False)

In [19]:
# 1. Define the column you want to check (e.g., 'col1')
#    Replace 'col1' with the actual column name you want to use for the condition.
condition_column = 'sum_click'

# 2. Create a boolean mask to identify the rows
#    This mask will be True for rows where the value in 'condition_column' is <= 1
mask = final_merge[condition_column] <= final_merge[condition_column].quantile(0.25)
#final_merge["sum_click"].describe() give 25 percentile =1


# 3. Use .loc to select rows based on the mask and set the 'burnout' column
final_merge.loc[mask, 'burnout'] = 1

In [31]:
print(mask)

0        False
1         True
2        False
3         True
4        False
         ...  
28780    False
28781    False
28782    False
28783    False
28784    False
Name: engagement_slope, Length: 28785, dtype: bool


In [37]:
print((final_merge["burnout"]==1).sum())
#print(final_merge.loc[final_merge["burnout"]==1])


3630080


In [38]:
print((final_merge["burnout"]==0).sum())


556156


In [42]:
final_merge["sum_click"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 4186236 entries, 0 to 4186235
Series name: sum_click
Non-Null Count    Dtype  
--------------    -----  
3988292 non-null  float64
dtypes: float64(1)
memory usage: 31.9 MB


In [20]:
final_merge.to_csv("percentance_0.25.csv", index=False)

In [21]:
#Missed or failed most assessments	
# 1. Define the column you want to check (e.g., 'col1')
#    Replace 'col1' with the actual column name you want to use for the condition.
condition_column = 'score'

# 2. Create a boolean mask to identify the rows
#    This mask will be True for rows where the value in 'condition_column' is <= 1
mask = final_merge[condition_column] <= 30
#final_merge["sum_click"].describe() give 25 percentile =1


# 3. Use .loc to select rows based on the mask and set the 'burnout' column
final_merge.loc[mask, 'burnout'] = 1

In [ ]:
final_merge.info()

In [22]:
# 1. Define the column to check
condition_column = 'final_result'

# 2. Create a boolean mask for Withdrawn or Fail
mask = final_merge[condition_column].isin(['Withdrawn', 'Fail'])

# 3. Set burnout = 1 for those rows
final_merge.loc[mask, 'burnout'] = 1


In [24]:
final_merge.to_csv("final_result_done.csv", index=False)

In [23]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4186236 entries, 0 to 4186235
Data columns (total 22 columns):
 #   Column                Dtype  
---  ------                -----  
 0   code_module           object 
 1   code_presentation     object 
 2   id_student            int64  
 3   gender                object 
 4   region                object 
 5   highest_education     object 
 6   imd_band              object 
 7   age_band              object 
 8   num_of_prev_attempts  int64  
 9   studied_credits       int64  
 10  disability            object 
 11  final_result          object 
 12  id_assessment         float64
 13  date_submitted        float64
 14  is_banked             float64
 15  score                 float64
 16  date_registration     float64
 17  date_unregistration   float64
 18  id_site               float64
 19  date                  float64
 20  sum_click             float64
 21  burnout               int64  
dtypes: float64(9), int64(4), object(9)
memory 

In [26]:
from scipy.stats import linregress


In [29]:
final_merge.to_csv("final_result.csv", index=False)

In [46]:
final_merge["code_presentation"].unique()

array(['2013J', '2014J', '2013B', '2014B'], dtype=object)

In [48]:
final_merge["is_banked"].unique()

array([ 0., nan,  1.])

In [62]:
final_merge["date_unregistration"].unique()

array([  nan,   12.,   96.,   72.,  175.,  135.,   30.,  144.,  129.,
         58.,  158.,  191.,  123.,   60.,  185.,  166.,  109.,  170.,
        187.,  177., -121.,   -3.,   53.,   65.,  160.,   51.,    5.,
        202., -100.,  172.,  119.,   73.,  128.,  241.,   23.,  173.,
        203.,   27.,   37.,  103.,   -2.,  240.,  138.,  163.,   10.,
        178.,  -19.,  -50.,  -80.,  242.,  220.,  114.,  219.,   13.,
        199.,   93.,   39.,  164.,  235.,  207.,  143.,   24.,  234.,
        104.,  201.,   67.,  -87.,  229.,  132., -101.,  -47.,  165.,
        227.,   18.,  174., -137.,  -12.,   80.,  -22.,  150.,  -11.,
       -129.,    9.,  228.,  180.,  182.,  213.,   63.,   32.,  108.,
        110.,   34.,   55.,  146.,  -16.,  -54.,   38.,  226.,   -8.,
        153.,  139.,   59.,   86.,  -75.,   42.,   -4.,  -59., -225.,
        157.,   68.,   11.,   76.,   33.,   25.,    6.,  -68.,   -9.,
        -65.,  -25.,  -92.,   -1.,   -5.,  208.,   95.,   48.,  -82.,
        198.,   22.,

In [61]:
max((final_merge["date_unregistration"].unique()))

np.float64(nan)

In [57]:
len(final_merge["date_unregistration"].unique())

417

In [55]:
final_merge["date_unregistration"].isna().sum()

np.int64(3835695)

In [49]:
final_merge["score"].unique()

array([ 78.,  85.,  80.,  82.,  70.,  68.,  64.,  60.,  nan,  72.,  71.,
        74.,  88.,  75.,  69.,  30.,  63.,  35.,  79.,  50.,  65.,  62.,
        73.,  81.,  76.,  67.,  89.,  77.,  83.,  42.,  66.,  59.,  61.,
        38.,  86.,  18.,  49.,  57.,  55.,  84.,  47.,  51.,  56.,  53.,
        54.,  45.,  87.,  46.,  43.,  52.,  39.,  37.,  48.,  40.,  32.,
        90.,  58.,  93.,  28.,  44.,  33.,  41.,  94.,  91.,  95.,  36.,
        25.,  15.,  11.,  34.,   0.,  92.,  98.,  19.,  27.,  24.,  29.,
        20., 100.,   5.,  96.,  97.,  10.,  13.,  99.,  26.,  14.,   1.,
        22.,  12.,   8.,  17.,  23.,  21.,  16.,   9.,  31.,   6.,   7.,
         4.,   2.,   3.])

In [50]:
#Consistent drop in engagement over time
#    Replace 'col1' with the actual column name you want to use for the condition.
condition_column1 = 'score'
condition_column2='is_banked'

# 2. Create a boolean mask to identify the rows
#    This mask will be True for rows where the value in 'condition_column' is <= 1
mask1= final_merge[condition_column1] <= 30
mask2= final_merge[condition_column2]==1
#final_merge["sum_click"].describe() give 25 percentile =1
final_mask= mask1 & mask2

# 3. Use .loc to select rows based on the mask and set the 'burnout' column
final_merge.loc[final_mask, 'burnout'] = 1

In [51]:
final_merge.to_csv("all_condition_done.csv", index=False)